# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 393f2260312065a735ebfb37ba12cbb2b1356d14a5d4d3fc391336cfb9d00f5bbcd59f489b3157397690fc845613831f7c7210f2412be1692ea40fab78367645

test:
  secret_key_base: 12973e3dfd990908d51d806e3d795005e6298a2bcaffccae380989571e906f2619b04ea4ac384924745f9bc615bac246f05e5c8468851a79115dee79cdb6f0a2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
